"""initial schema

Revision ID: 6677f8f9a654
Revises: 
Create Date: 2026-06-29 14:35:03.064554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6677f8f9a654'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spotify_user_id', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_spotify_user_id'), 'users', ['spotify_user_id'], unique=True)
    op.create_table('listen_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.String(length=16), nullable=False),
    sa.Column('spotify_id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('artist', sa.String(length=512), nullable=False),
    sa.Column('spotify_url', sa.Text(), nullable=True),
    sa.Column('added_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_listen_list_spotify_id'), 'listen_list', ['spotify_id'], unique=False)
    op.create_index(op.f('ix_listen_list_user_id'), 'listen_list', ['user_id'], unique=False)
    op.create_table('lists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lists_user_id'), 'lists', ['user_id'], unique=False)
    op.create_table('ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.String(length=16), nullable=False),
    sa.Column('spotify_id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('artist', sa.String(length=512), nullable=False),
    sa.Column('spotify_url', sa.Text(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('review', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ratings_spotify_id'), 'ratings', ['spotify_id'], unique=False)
    op.create_index(op.f('ix_ratings_user_id'), 'ratings', ['user_id'], unique=False)
    op.create_table('list_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('list_id', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.String(length=16), nullable=False),
    sa.Column('spotify_id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('artist', sa.String(length=512), nullable=False),
    sa.Column('spotify_url', sa.Text(), nullable=True),
    sa.Column('added_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['list_id'], ['lists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_list_items_list_id'), 'list_items', ['list_id'], unique=False)
    op.create_index(op.f('ix_list_items_spotify_id'), 'list_items', ['spotify_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_list_items_spotify_id'), table_name='list_items')
    op.drop_index(op.f('ix_list_items_list_id'), table_name='list_items')
    op.drop_table('list_items')
    op.drop_index(op.f('ix_ratings_user_id'), table_name='ratings')
    op.drop_index(op.f('ix_ratings_spotify_id'), table_name='ratings')
    op.drop_table('ratings')
    op.drop_index(op.f('ix_lists_user_id'), table_name='lists')
    op.drop_table('lists')
    op.drop_index(op.f('ix_listen_list_user_id'), table_name='listen_list')
    op.drop_index(op.f('ix_listen_list_spotify_id'), table_name='listen_list')
    op.drop_table('listen_list')
    op.drop_index(op.f('ix_users_spotify_user_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
